name: GitHub Actions Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate docs
        uses: mattnotmitt/doxygen-action@v1.3.1
        with:
          doxyfile-path: 'Doxyfile'
          working-directory: 'docs'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: docs/html
